[[rp_productpages]]
=== Extension of existing product pages
Product pages that already exist in {sp} are equivalent to the <<rp_categorypages,category pages>> described in the previous chapter.
They can also be displayed and edited in the {cc} using the {ocm}.
This also requires the filling of the output channel of the {fs} page template and an adaptation of the corresponding Twig templates in Spryker.

[NOTE]
====
If there are references to categories or products within the {fs} project which have been deleted or are inactive in {sp}, so-called orphaned pages occur.
These can be removed from the project via the <<uc_orphanedpages,report `*Lost and Found*`>>.
====

// ********************************************* Seitenvorlage *********************************************
[[rp_pdp_pagetemp]]
==== Page template
Editing a product page is equivalent to extending a <<rp_categorypages,category page>> and is, in the {fs} project, also based on a page reference.
This and its associated page are automatically created in the background and invisible to the editor.

The page template `productpage` provided with the reference project represents a product page.
It maps the Twig template `pdp.twig` and comes with the {productpage_caas_channel}[output channel] displayed in the following code snippet.

.Output channel of the page template productpage
----
$CMS_TRIM(level:1)$
   $CMS_SET(json, {:})$
   $CMS_SET(previewId, previewId(element:#global.node))$
	$CMS_SET(void, json.put("previewId", "" + previewId))$
	$CMS_SET(void, json.put("pageRevisionId", #global.page.revision.id))$
	$CMS_SET(void, json.put("pagetype", "product"))$
	$-- Page uid is needed for later identification when setting the SKU of the page --$
	$CMS_SET(void, json.put("page_uid", #global.page.uid))$
	$CMS_SET(void, json.put("product_sku", pt_productSku))$
	$CMS_SET(blocks, [])$

	$CMS_VALUE(#global.page.body("content"))$
	$CMS_SET(void, json.put("blocks", blocks))$
  
	$CMS_VALUE(json.toJSON)$
$CMS_END_TRIM$
----

The output channel of the {productpage_caas_channel}[product page] and the {categorypage_caas_channel}[category page] are almost identical.
They only differ in the specification of the Page UID, the Product SKU and in the number of content areas.
The Product SKU is a unique product ID which, together with the Page UID, is used to uniquely identify the product page in {sp}.
By using the script {script_set_sku}[`set_product_sku`], the Product SKU is automatically saved in the form of the page when a product page is created in the {fs} project.

// ********************************************* Twig-Template *********************************************
[[rp_pdp_twigtemp]]
==== Twig template
The Twig template `product-cms-block.twig` represents a product section on the {sp} side and extends the parent template `pdp.twig`, in which the basic layout of all product pages is defined.
It is a part of the zip file `b2c-demo-shop-extensions-<VERSION>.zip` included in the delivery and must be stored under the path`*src/Pyz/Yves/CmsBlockWidget/Theme/default/components/molecules/product-cms-block*` in {sp}.

The template `pdp.twig` requires the following adaptation to enable the integration of product sections.

.Adaptation of the Twig template pdp.twig
----
[...]
<div class="container__inner">
   {% include molecule('product-detail', 'ProductDetailPage') with {
      [...]
   } only %}

   {% include molecule('product-cms-block', 'CmsBlockWidget') ignore missing with {
      data: {
         idProductAbstract: data.product.idProductAbstract,
      }
   } only %}
</div>
[...]
----

The following code example shows the content of the Twig template `product-cms-block.twig`.
It first contains the name of the molecule and specifies that the specification of a Product SKU is required.
This is passed to the Twig template via the parent Twig template `pdp.twig`.
The block `body` is used to output the contents that are maintained for the corresponding product page.

.Twig template product-cms-block.twig
----
{% extends model('component') %}

{% define config = {
   name: 'product-cms-block'
} %}

{% define data = {
   idProductAbstract: required
} %}

{% block body %}
   {{ fsSpyCmsBlock({ product: data.idProductAbstract }) }}
{% endblock %}
----
