include::../../variables.adoc[]
== Introduction
{fs} is used to create versatile and project-specific content.
Thanks to the _{modulname} for {sp} {os}_ module, it is possible to transfer these contents to the e-commerce shop system {sp} {os} and use it there.

[NOTE]
====
In the remainder of the document the abbreviated form "{sp}" is used instead of "{sp} {os}". 

Furthermore, the entire documentation is geared towards connecting to the {sp} B2C Demo Shop in version 202009.0.
Mention of the shop therefore refers exclusively to the B2C Demo Shop.
====

The module combines the functional strengths of both systems, delivering the key advantages and create a successful overall system made up of two areas that work in parallel and are largely decoupled from one another:

Components on the {fs} side::
These components are used for creating and maintaining editorial data. 
The data is transferred in JSON format to the relevant _{c}_ instance, and queried from there by {sp}.

Components on the {sp} side::
These components are used for the integration of the editorial content created in {fs}.
{sp} imports this data and integrates it into the shop.

Included in the delivery of the _{modulname} for {sp} {os}_ module is the reference project _{refproject}_, which is available as a {refproject_github}[GitHub repository].
This documentation is consistently based on the reference project and provides an explanation of the functions made available by the module using common use cases. 

[NOTE]
====
This document is aimed at both {sp} and {fs} developers, who should be able to perform the integration using this document as a guide. +
It is *not* intended as a manual for {fs} editors.

It is assumed that the reader is confident in the use of {fs} and {sp} as well as _{c}_ and _{ocm}_.
====

////

// Funktionsumfang
include::functions.adoc[]

// Architektur
include::architecture.adoc[]

// Konzept
include::concept.adoc[]

// Technische Voraussetzungen
include::requirements.adoc[]

// Wichtige Hinweise
include::important-information.adoc[]

////