[[sfcc_job_schedules]]
=== Setting up the job schedules
To import the content and <<slot_configuration,slot configurations>> generated by {fs} into {ccloud}, a job schedule must be created in {ccloud} for each site.
Therefore, the _metadata_ directory of the delivery contains the zip file _importExamples.zip_, which requires an <<sfcc_zip_file_import,import>> into the {ccloud} as described previously.

The jobs imported with the zip file have the job IDs `{fs}-Import-RefArch` and `{fs}-Import-RefArchGlobal` by default.
The ID ensures the uniqueness of the jobs for the different sites and can be adjusted as required on the `*menu:Administration[Operations>Jobs]*` page.
It is recommended to include the ID of the respective site in the corresponding job ID to ensure uniqueness.

The job schedules configured in the file consist of three job steps.
These are of the types `Import Content`, `Import Content Slots`, and `Rebuild Search Index`.
All three job steps initially have the scope `RefArch` or `RefArchGlobal`, which must be changed to the appropriate site.
In addition, these define different parameters whose default values can be kept mostly. 
Only the parameters `WorkingFolder` and `FileNamePattern` need to be adapted to the specific project.
The editing dialog opens by clicking on the job step's name.

WorkingFolder::
The parameter `WorkingFolder` specifies - relative to the `*IMPEX*` directory - the path to the directory containing the XML files generated by {fs}.
Its value must be identical for both job steps.

FileNamePattern::
The parameter defines the name of the XML files generated by {fs}. 
In the case of the `ImportContent` job step, it must have the `fs_import_library.xml` value and for the `ImportContentSlots` job step, it must have the `fs_import_slot_configuration.xml` value.

[NOTE]
====
General information about creating job schedules can be found in the {ccloud} documentation in chapter
https://documentation.demandware.com/DOC2/topic/com.demandware.dochelp/Jobs/CreatingJobs.html[menu:Administering Your Organization[Jobs>Creating Jobs]]

The three job steps and their parameters are described in the {ccloud} documentation in the chapters
https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FDWAPI%2Fjobstepapi%2Fhtml%2Fapi%2Fjobstep.ImportContent.html[_ImportContent_],
https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FDWAPI%2Fjobstepapi%2Fhtml%2Fapi%2Fjobstep.ImportContentSlots.html[_ImportContentSlots_], and
https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FDWAPI%2Fjobstepapi%2Fhtml%2Fapi%2Fjobstep.SearchReindex.html[_SearchReindex_].
====