=== Using WebDAV with https
To use the WebDAV server with `https` instead of `http`, it is not necessary to perform any additional configuration work.
However, a local certificate authority managed by the company is normally used for `https`.
The certificate in question, including the entire chain up to the certificate on the WebDAV server, must be made available to the {fs} server's JVM.

[NOTE]
====
The JVM expects public certificates of this kind to be in the form of a `PKCS12` file or a `JKS` file.
====

Using the command below, import the public root or intermediate certificates into a `JKS` file and select btn:[Yes] in answer to the question whether the certificate is to be trusted.
You must repeat this process for each certificate.

[source]
// codeAnfang
----
keytool -import -file cert1.crt -keystore truststore.jks –storepass changeit
----
// codeEnde

Copy the `Trust Store` that is generated into the `*menu:firstspirit5[conf]*` directory of your {fs} server and add the following lines to the file `*menu:firstspirit5[conf>fs-wrapper.conf]*`.

[source]
// codeAnfang
----
wrapper.java.additional.100=-Djavax.net.ssl.trustStore=conf/truststore.jks
wrapper.java.additional.101=-Djavax.net.ssl.trustStorePassword=changeit
wrapper.java.additional.102=-Djavax.net.ssl.trustStoreType=JKS
----
// codeEnde

[IMPORTANT]
====
The parameters must be activated by restarting the {fs} Server.
====

If the WebDAV server is expecting mutual SSL authentication, you must use the following calls to create and sign a client certificate as a first step.

[source]
// codeAnfang
----
openssl genrsa -out private.key 2048
openssl req -new -key private.key -out request.csr
----
// codeEnde

The file `request.csr` is sent to the certificate authority, which responds with the file `cert.crt`.
The private key, the public certificate, and the certificate from the certificate authority must then be collected in a `Key Store` to be read by the `JVM`.

[source]
// codeAnfang
----
cd firstspirit5/conf
openssl pkcs12 -export -in public.crt -inkey private.key \
-out clientcert.p12 -CAfile authority.crt
----
// codeEnde

If the certificate chain consists of one or more intermediate certificates, you can import them via `keytool`.

[source]
// codeAnfang
----
keytool -import -file intermediate1.crt -trustcacerts \
-keystore clientcert.p12 -storepass changeit
----
// codeEnde

The `Key Store` can be transferred to the `JVM` of the {fs} Server by adding the following lines to `*menu:firstspirit5[conf>fs-wrapper.conf]*`.

[source]
// codeAnfang
----
wrapper.java.additional.103=-Djavax.net.ssl.keyStore=conf/clientcert.p12
wrapper.java.additional.104=-Djavax.net.ssl.keyStorePassword=changeit
wrapper.java.additional.105=-Djavax.net.ssl.keyStoreType=PKCS12
----
// codeEnde
