[[existingcpoutput]]
==== Page template
Generally, content pages in a {fs} project are edited based on a {fs} page reference.
This reference and the page on which it is based must be created for content pages that already exist in {ccloud}.
In the _{refproject}_, the creation of this page reference and the associated page takes place in the background, in a process that is invisible to the editor.
The script `page_type_mapping` uses the page template of the {ccloud} page to determine the corresponding {fs} page template, which is referenced in the <<install_pset,project settings>>.

When a content page is created, the ID of the associated {ccloud} page is stored in its form.
This ID is required to display the page in the preview.
The page template therefore contains the hidden input component `pt_cc_identifier`.
If additional page templates are added to the project, their form must also contain this input component.

[source,html]
.Input component pt_cc_identifier
----
<CMS_INPUT_TEXT name="pt_cc_identifier" hFill="yes" hidden="yes" useLanguages="no">
   <LANGINFOS>
      <LANGINFO lang="*" label="Commerce Cloud Identifier"/>
   </LANGINFOS>
</CMS_INPUT_TEXT>
----

The following code extract shows a shortened form of the presentation channel for the page template in the reference project:

[[pagetemplatechannel]]
[source,html]
.Presentation channel for the page template
----
$CMS_TRIM(level:1)$
   $CMS_SET(json, {:})$
   $CMS_SET(previewId, previewId(element:#global.node))$
   $CMS_SET(void, json.put("previewId", "" + previewId))$
   $CMS_SET(void, json.put("pageRevisionId", #global.page.revision.id))$
   
   $CMS_SET(slotList, {:})$
   
   $CMS_IF(#global.page.body("stage_body").children.toList().size > 0)$
      $CMS_SET(dynamicContent, {:})$
      $CMS_SET(content)$
         $CMS_TRIM(level:4)$$CMS_VALUE(#global.page.body("stage_body"))$$CMS_END_TRIM$
      $CMS_END_SET$
      $CMS_SET(stage_body, {:})$
      $CMS_SET(void, stage_body.put("content", content.toString))$
      $CMS_SET(void, stage_body.put("dynamic", 
         if(dynamicContent.get("active") != null, dynamicContent.get("active"), false)))$
      $CMS_SET(void, slotList.put("stage_body", stage_body))$
   $CMS_END_IF$
   
   [...]
   
   $CMS_SET(void, json.put("slots", slotList))$
   $CMS_VALUE(json.toJSON)$
$CMS_END_TRIM$
----

The page has three content areas - the `stage_body`, `tiles_body`, and `main_body` - and represents a `landingLayout2Page.jsp` page.
While the first two content areas are used to edit existing content from {ccloud}, the third allows further sections to be added.
In the reference project, the section templates `banner_section`, `category_teaser_section`, and `text_picture_section` are available for this purpose.
The content of these templates is added to the JSON object `slots` generated in the template.

For this purpose, two instructions are required for each content area to enable the system to distinguish between static and <<dynamiccontent,dynamic content>>.
Dynamic content can only be incorporated into combined text-image sections, as this is the only type of section that can include dynamic product data.
The section uses the link template `a_product_price_link`, with the value of the `active` parameter in the presentation channel configured as `true` for the `dynamicContent` variable.

In addition to the editorial content, the `previewId` and `pageRevisionId` of the page reference are also transferred to the JSON object created in the template:
The `previewId` is stored in the `PAGE_PREVIEW_DATA` object in the template in {ccloud}, and is used to identify the page reference.
Identification takes places via the <<javascript,JavaScript of _{ocm}_>>.
The `pageRevisionId` is a technical dependency field and ensures that <<dynamiccontent,dynamic content>> is always displayed correctly in {wc}.

The JSON object is part of the _{c}_ item to be generated and can be read out within the <<ccpagetemplate,{ccloud} templates>>.
