include::../../variables.adoc[]
== Introduction
{fs} is used to create versatile and project-specific content.
Thanks to the _{modulname} for {sp} {os}_ module, it is possible to transfer these contents to the e-commerce shop system {sp} {os} and use it there.

[NOTE]
====
In the remainder of the document the abbreviated form "{sp}" is used instead of "{sp} {os}". 
====

The module combines the functional strengths of both systems, delivering the key advantages and create a successful overall system.
This system is made up of components on both the {fs} and {sp} side, which work in parallel and are largely decoupled from one another.

This document is intended for server administrators and therefore only describes the installation and configuration of the module as well as the import of the reference project on the {fs} server.
All steps to be performed in the project and the functionalities provided with the integration are described in the {sprykerdocen}[_{modulname} for {sp} Commerce OS documentation_].

// Funktionsumfang
include::../introduction/functions.adoc[]

// Architektur
include::../introduction/architecture.adoc[]

// Technische Voraussetzungen
include::../introduction/requirements.adoc[]